### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by RussellGrayxd** [vinayudyawer/KUD3D#1]
Dead link apparently, keep getting and error in the install. 

Error: Failed to install 'KUD3D' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Russe/AppData/Local/Temp/RtmpANfYSb/filee9b034ac7c14/KUD3D_0.1.0.tar.gz’ had non-zero exit status

**Comment by vinayudyawer** [comment]
Hey Russell,

Can you provide more details, I can't replicate your error. Please provide system details, and the full error message when you run 
`devtools::install_github("vinayudyawer/KUD3D")`

Cheers
Vinay

**Comment by RussellGrayxd** [comment]
Running R 3.6.2 on Windows 10 OS, Asus Rogstrix laptop
This is the full message after devtools (I opted out of updating other packages):

> devtools::install_github("vinayudyawer/KUD3D")Downloading GitHub repo vinayudyawer/KUD3D@masterThese packages have more recent versions available.It is recommended to update all of them.Which would you like to update?
 1: All                                        2: CRAN packages only                         3: None                                       4: dplyr        (0.8.3    -> 0.8.5   ) [CRAN] 5: rlang        (0.4.3    -> 0.4.5   ) [CRAN] 6: vctrs        (0.2.2    -> 0.2.4   ) [CRAN] 7: digest       (0.6.23   -> 0.6.25  ) [CRAN] 8: glue         (1.3.1    -> 1.3.2   ) [CRAN] 9: sp           (1.3-2    -> 1.4-1   ) [CRAN]10: lifecycle    (0.1.0    -> 0.2.0   ) [CRAN]11: jsonlite     (1.6      -> 1.6.1   ) [CRAN]12: shiny        (1.4.0    -> 1.4.0.2 ) [CRAN]13: crosstalk    (1.0.0    -> 1.1.0.1 ) [CRAN]14: manipulat... (0.10.0   -> 0.10.1  ) [CRAN]15: yaml         (2.2.0    -> 2.2.1   ) [CRAN]16: mime         (0.8      -> 0.9     ) [CRAN]17: stringi      (1.4.4    -> 1.4.6   ) [CRAN]18: callr        (3.4.1    -> 3.4.2   ) [CRAN]19: processx     (3.4.1    -> 3.4.2   ) [CRAN]20: ps           (1.3.0    -> 1.3.2   ) [CRAN]21: testthat     (2.3.1    -> 2.3.2   ) [CRAN]22: cli          (2.0.1    -> 2.0.2   ) [CRAN]23: mvtnorm      (1.0-11   -> 1.1-0   ) [CRAN]24: rgl          (0.100.47 -> 0.100.50) [CRAN]25: ggplot2      (3.2.1    -> 3.3.0   ) [CRAN]26: tidyselect   (0.2.5    -> 1.0.0   ) [CRAN]
Enter one or more numbers, or an empty line to skip updates:
√  checking for file 'C:\Users\Russe\AppData\Local\Temp\RtmpANfYSb\remotese9b05fb6c49\vinayudyawer-KUD3D-5cd0ef2/DESCRIPTION' (479ms)-  preparing 'KUD3D': (1s)√  checking DESCRIPTION meta-information ... -  checking for LF line-endings in source and make files and shell scripts-  checking for empty or unneeded directories-  looking to see if a 'data/datalist' file should be added-  building 'KUD3D_0.1.0.tar.gz' (339ms)   Installing package into ‘C:/Users/Russe/Documents/R/win-library/3.6’(as ‘lib’ is unspecified)* installing *source* package 'KUD3D' ...** using staged installation** R** data*** moving datasets to lazyload DB** byte-compile and prepare package for lazy loadingError: (converted from warning) package 'ks' was built under R version 3.6.3Execution haltedERROR: lazy loading failed for package 'KUD3D'* removing 'C:/Users/Russe/Documents/R/win-library/3.6/KUD3D'Error: Failed to install 'KUD3D' from GitHub:  (converted from warning) installation of package ‘C:/Users/Russe/AppData/Local/Temp/RtmpANfYSb/filee9b043b757b7/KUD3D_0.1.0.tar.gz’ had non-zero exit status

--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Monday, March 16, 2020, 02:28:10 a.m. GMT+7, Vinay Udyawer <notifications@github.com> wrote:  
 
 


Hey Russell,

Can you provide more details, I can't replicate your error. Please provide system details, and the full error message when you run
devtools::install_github("vinayudyawer/KUD3D")

Cheers
Vinay

**Comment by vinayudyawer** [comment]
This looks likes there is an error in loading the 'ks' package dependency. Perhaps updating the other packages might help installing 'KUD3D'

**Comment by RussellGrayxd** [comment]
I have now updated all packaged, including ks, and still get the same error. 
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, March 17, 2020, 02:15:38 a.m. GMT+7, Vinay Udyawer <notifications@github.com> wrote:  
 
 


This looks likes there is an error in loading the 'ks' package dependency. Perhaps updating the other packages might help installing 'KUD3D'

**Comment by RussellGrayxd** [comment]
I updated from R 3.6.2 to R 3.6.3 and the package downloaded fine. May be worth mentioning in the repository in case anyone else runs into the issue. 
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, March 17, 2020, 08:49:13 a.m. GMT+7, Russell Gray <russell_graypt@yahoo.com> wrote:  
 
 I have now updated all packaged, including ks, and still get the same error. 
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, March 17, 2020, 02:15:38 a.m. GMT+7, Vinay Udyawer <notifications@github.com> wrote:  
 
 


This looks likes there is an error in loading the 'ks' package dependency. Perhaps updating the other packages might help installing 'KUD3D'

**Comment by vinayudyawer** [comment]
Thanks Russell, 

Good to know, Ill make some changes to make the 'KUD3D' package reverse compatible, but the requirement for the most up-to-date R version might also affect the installing of dependencies. Ill make it apparent in the vignette.

Cheers
Vinay
