### ISSUE TITLE
points are offset from 3d map

### ISSUE THREAD

**Issue by RussellGrayxd** [vinayudyawer/KUD3D#2]
Hey again, 
I'm running:

#plot 3d map
scene <- elev_matrix %>%
  sphere_shade(texture = "imhof1") %>%
  add_shadow(raymat, max_darken = 0.5) %>%
  add_shadow(ambmat, max_darken = 0.5) %>%
  add_overlay(overlay_img, alphalayer = 0.9) 

#Render the 'rayshader' scene
rayshader::plot_3d(
  scene,
  elev_matrix,
  zscale = 25,
  solid = FALSE,
  shadow = TRUE
) 

## Plot 3DKUD ontop of map
GW2.tib %>%
  transmute(lat = coords.x2,
            lon = coords.x1,
            dep = elevation) %>%
  add_fkud(
    ras = elev.crop,
    zscale = 25,
    cont = c(95, 50),
    alphavec = c(0.1, 0.9),
    drawpoints = T,
    size = 1,
    col.pt = "black",
    colors = c("red","red")
  )

and for some reason the data is offset from the 3d map, I can see the elevation and everything in the points matching where the mountains on the map should be, but I can't for the life of me figure out how to reposition it. Any ideas? I've checked the raster and point data and they match up exactly as you can see in the mapview on the right. 
![00000](https://user-images.githubusercontent.com/30756433/76771367-d3f38880-67d1-11ea-9666-aebadc21730a.png)

**Comment by RussellGrayxd** [comment]
The last post was from data all in lat long... I tried converting everything to UTM and now I get this error when I run add_fkud:

 Error in chol.default(S) : 
  the leading minor of order 2 is not positive definite

**Comment by vinayudyawer** [comment]
This has to do with the code within the `add_fkud`, `add_points` and `add_axes` functions. The points and KUD voxels are rescaled before being plotted onto the 3D rgl environment. Since I wrote these functions the `rayshader` package has slightly modified how it rescales its 3D environment. I have updated the code in this repository in line with the `rayshader` updates. Try reinstalling the package and re-running the code.

You should be able to use the lat/lon version. Let me know how you go.

**Comment by RussellGrayxd** [comment]
I haven't been able to install the package to begin with, I have been copy/pasting the function codes themselves into the R console and running them from there. If they are the most updated version there shouldn't be an issue, but there still is. 
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, March 17, 2020, 02:40:13 a.m. GMT+7, Vinay Udyawer <notifications@github.com> wrote:  
 
 


This has to do with the code within the add_fkud, add_points and add_axes functions. The points and KUD voxels are rescaled before being plotted onto the 3D rgl environment. Since I wrote these functions the rayshader package has slightly modified how it rescales its 3D environment. I have updated the code in this repository to in line with the rayshader updates. Try reinstalling the package and re-running the code.

You should be able to use the lat/lon version. Let me know how you go.

**Comment by RussellGrayxd** [comment]
I've finally got everything to work as it should, if R isn't updated to the latest version (mine was 3.6.2) the install and the functions don't work properly. 
By the way, is there any way to save the KDE overlay with the map using the save_obj() function by rayshader??
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, March 17, 2020, 08:50:52 a.m. GMT+7, Russell Gray <russell_graypt@yahoo.com> wrote:  
 
 I haven't been able to install the package to begin with, I have been copy/pasting the function codes themselves into the R console and running them from there. If they are the most updated version there shouldn't be an issue, but there still is. 
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, March 17, 2020, 02:40:13 a.m. GMT+7, Vinay Udyawer <notifications@github.com> wrote:  
 
 


This has to do with the code within the add_fkud, add_points and add_axes functions. The points and KUD voxels are rescaled before being plotted onto the 3D rgl environment. Since I wrote these functions the rayshader package has slightly modified how it rescales its 3D environment. I have updated the code in this repository to in line with the rayshader updates. Try reinstalling the package and re-running the code.

You should be able to use the lat/lon version. Let me know how you go.

**Comment by vinayudyawer** [comment]
Unfortunately the `save_obj()` function might not work with altered `rayshader` outputs. You can however save the output as an interactive html using the `rgl::writeWebGL()` function and interact with them using a web browser.
